steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/americanas-joao-test/stream_simulate', '--file=./docker/Dockerfile', '.']
images: ['gcr.io/americanas-joao-test/stream_simulate']
